name: Publish Docker image
on: [pull_request]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: Extract branch name
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "##[set-output name=branch;]${GITHUB_REF#refs/heads/}"
        id: extract_branch
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build tagged image
        uses: docker/build-push-action@v4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          push: true
          tags: |
            ghcr.io/valhalla/valhalla:${{ steps.extract_branch.outputs.branch }}
      - name: Build latest image
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: |
            ghcr.io/valhalla/valhalla:latest

